server:
  port: 8001

# 注册在eureka服务列表只能够的名称
spring:
  application:
    name: microservice-provider-user

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-user8001
    prefer-ip-address: true  #访问路径可以显示IP地址